### ISSUE TITLE
Use multiple validations on a single value

### ISSUE THREAD

**Issue by irumvanselme** [veritem/valdie#12]
What if we want to check if a value is string, with 2 minimum characters and 10 maximum characters

**Comment by claranceliberi** [comment]
> What if we want to check if a value is a string, with 2 minimum characters and 10 maximum characters

you mean something like this  ?
```js
const name = "myName"
name.isString().man(2).max(10)
```

**Comment by makuzaverite** [comment]
That's a really cool idea will look into this in near future

**Comment by veritem** [comment]
Thank you so much for the cool idea, I had around it today and go it working 👍
